name: 💡 Feature Request
description: Suggest an idea for this integration.
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      placeholder: I would love to see...
    validations:
      required: true